//https://internet.ocbc.com.my/internet-banking/Content/Include/MY/en/FundTransfer/ManagePayeeFT/Bank_%20account_info.html
final String bankData = '[{"id":"1","name":"Affin Bank Berhad","lenght":12 },'
    '{"id":"2","name":"Alliance Bank Malaysia Berhad","lenght":15},'
    '{"id":"3","name":"AmBank (M) Berhad","lenght":13},'
    '{"id":"4","name":"Bangkok Bank Berhad","lenght":10},'
    '{"id":"5","name":"Bank of America Malaysia Berhad","lenght":5},'
    '{"id":"6","name":"Bank of China (Malaysia) Berhad","lenght":10},'
    '{"id":"7","name":"BNP Paribas Malaysia Berhad","lenght":10},'
    '{"id":"8","name":"China Construction Bank (Malaysia) Berhad","lenght":10},'
    '{"id":"9","name":"CIMB Bank Berhad","lenght":10},'
    '{"id":"10","name":"Citibank Berhad","lenght":10},'
    '{"id":"11","name":"Deutsche Bank (Malaysia) Berhad","lenght":10},'
    '{"id":"12","name":"Hong Leong Bank Berhad","lenght":10},'
    '{"id":"13","name":"HSBC Bank Malaysia Berhad","lenght":10},'
    '{"id":"14","name":"India International Bank (Malaysia) Berhad","lenght":10},'
    '{"id":"15","name":"Industrial and Commercial Bank of China (Malaysia) Berhad","lenght":10},'
    '{"id":"16","name":"J.P. Morgan Chase Bank Berhad","lenght":10},'
    '{"id":"17","name":"Malayan Banking Berhad","lenght":10},'
    '{"id":"18","name":"Mizuho Bank (Malaysia) Berhad","lenght":10},'
    '{"id":"19","name":"MUFG Bank (Malaysia) Berhad","lenght":10},'
    '{"id":"20","name":"OCBC Bank (Malaysia) Berhad","lenght":10},'
    '{"id":"21","name":"Public Bank Berhad","lenght":10},'
    '{"id":"22","name":"RHB Bank Berhad","lenght":10},'
    '{"id":"23","name":"Standard Chartered Bank Malaysia Berhad","lenght":10},'
    '{"id":"24","name":"Sumitomo Mitsui Banking Corporation Malaysia Berhad","lenght":10},'
    '{"id":"25","name":"The Bank of Nova Scotia Berhad","lenght":10},'
    '{"id":"26","name":"United Overseas Bank (Malaysia) Bhd","lenght":10}'
    ']';
